version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/app:cached
      - ~/.gitconfig:/home/vscode/.gitconfig:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - github-runner-data:/home/vscode/actions-runner:cached
    env_file:
      - ../.env
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      # Add these environment variables if they're not in .env file
      - GITHUB_PERSONAL_TOKEN=${GITHUB_PERSONAL_TOKEN}
      - GITHUB_REPOSITORY=${GITHUB_REPOSITORY}
      # NVIDIA settings
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    # Enable ptrace for debuggers
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    # Avoid terminal issues
    init: true
    # Keep container running for VS Code
    command: sleep infinity

volumes:
  github-runner-data: